services:
  - type: web
    name: backend
    env: python
    plan: free
    rootDir: ./backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: ENVIRONMENT
        value: production
