name: Build and deploy to development environment

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r backend/requirements.txt

  build-frontend:
    name: Build Frontend
    needs: build-backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          VITE_BASE_URL="https://zpi2024-zaoczni-orzel.onrender.com"
          npm run build

      - name: Upload frontend build
        uses: actions/upload-artifact@v3
        with:
          name: frontend-dist
          path: frontend/dist

  deploy-backend:
    name: Deploy Backend to Render (Development)
    needs: build-backend
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Trigger backend deployment
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"branch": "develop"}' \
          https://api.render.com/v1/services/ZPI2024_zaoczni_Orzel/deploys

  deploy-frontend:
    name: Deploy Frontend to GitHub Pages (Development)
    needs: [build-frontend, deploy-backend]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download frontend build
        uses: actions/download-artifact@v3
        with:
          name: frontend-dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
          destination_dir: development
