name: Build and deploy to production environment

on:
  push:
    branches:
      - develop

jobs:
  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r backend/requirements.txt

  deploy-backend:
    name: Deploy Backend to Render
    needs: build-backend
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger backend deployment
        run: |
          curl -s -X POST \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_TOKEN }}" \
          -H "Content-Type: application/json" \
              -d '{}' \
              https://api.render.com/v1/services/${{ secrets.RENDER_DEV_ID }}/deploys

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Build frontend
        env:
          DEPLOY_BASE: "/ZPI2024_zaoczni_Orzel/development/"
          VITE_BASE_URL: "https://zpi2024-zaoczni-orzel.onrender.com"
        run: |
          cd frontend
          npm install
          npm run build

      - name: Upload frontend build
        uses: actions/upload-artifact@v3
        with:
          name: frontend-dist
          path: frontend/dist

  deploy-frontend:
    name: Deploy Frontend to GitHub Pages
    needs: [build-frontend]
    runs-on: ubuntu-latest

    steps:
      - name: Download frontend build
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          destination_dir: development