name: Run Unit Tests

on:
  pull_request:
    branches:
      - main
      - release
      - develop

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r backend/requirements.txt

      # Step 4: Run tests
      - name: Run Unit Tests
        run: |
          source venv/bin/activate
          pytest backend/tests/ -v --tb=short

      # Step 5: Display test results
      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: backend/.pytest_cache/
